## Check anaconda.org for new package versions
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - fastqc=0.11.9
 - fastp=0.20.1
 - star=2.7.7a
 - subread=2.0.1
 - gatk4=4.2.0.0
 - samtools=1.11
 - bcftools=1.11