__default__ :
        job-name        : "{rule}"
        output          : "snakemake/logs/{rule}/{wildcards}.log"
        ntasks          : "{resources.ntasks}"
        cpus-per-task   : "{resources.cpu}"
        mem             : "{resources.mem_mb}M"
        time            : "00-{resources.hours}:{resources.mins}:00"
        gres            : null
        account         : "my_account"
        partition       : "my_partition"

# Override the above defaults with job specific values
# align:
#         cpus-per-task   : 4
#         mem             : "8G"
#         time            : "00-01:00:00"

# Job specific resource requirements can be passed from the rule, in the Snakefile, via the "resources" keyword
# example:
#        cpus-per-task : "{resources.cpu}"
#        mem           : "{resources.mem_mb}"
#        time          : "00-00:{resources.time}:00"
